### ISSUE TITLE
Python 3.5 test_diagnostic_plots fail on Mac OS X

### ISSUE THREAD

**Issue by cdeil** [zblz/naima#104]
I'm getting this error with Python 3.5 on Mac OS X:
```
INTERNALERROR> OSError: [Errno 24] Too many open files
```
https://gist.github.com/cdeil/80129d9e48eca2558087#file-gistfile1-txt-L113

@zblz  - Can you reproduce? Maybe add a Mac Python 3.5 test on travis-ci?

**Comment by zblz** [comment]
From a bit of searching it seems this error is very platform-dependent and there is no clear way to avoid it. I'll add a test on travis to see if it fails there and try to close figures in the tests.

**Comment by zblz** [comment]
Testing on Travis, I have managed to avoid this error by using the master version of matplotlib, which includes this fix https://github.com/matplotlib/matplotlib/pull/5295. This will only go in mpl 2.0, so in the meantime the tests in osx and Py35 will fail at this stage.

@cdeil: I'll close this issue since there is not much to do on our side, just wait for the next version of mpl. If this also happens during normal use (i.e., not firing off the tens of calls to plot routines in test_plotting), please reopen it.
