### ISSUE TITLE
Implementing redshift attenuation

### ISSUE THREAD

**Issue by TarekHC** [zblz/naima#117]
Hi @zblz , 

I have been playing with naima for some time now, and I was wondering if there is any way of including redshift attenuation to existing models. I'm not sure if it's implemented, but at least I did not find it in the documentation.

I saw the "TableModel", which I guess would be ideal to interpolate the absorption values from the typical tables (Dominguez, Franceschini, etc..). I could implement and test it myself (or at least try), but I would like to know the best approach you can think about.

Creating a new "Table model" containing each EBL model opacity values? Then these table models could be used multiplying your own model. Does it make sense to you?

Cheers!

Tarek

**Comment by zblz** [comment]
Indeed, it is not implemented and would be a useful addition. `TableModel` should be a good starting point because all the interpolation stuff is already there. You could just add a wrapper around that that reads the different tables depending on a keyword. If you want to implement it, please go ahead! You can open a pull request even if it is not finished so you can ping me there if you need help implementing anything.

**Comment by TarekHC** [comment]
Ok, that seems relatively easy. I'm not a python expert, but I may be able to do that myself. It does not look like too much work either.  

If I get to the point of a naive working example, or at least something close to it I'll pull request and implement your comments. 

I'm happy! :)  This could be a good exercise to improve my python skills...

Cheers Victor

**Comment by zblz** [comment]
Fixed in #119.
