### ISSUE TITLE
How to deal with the upper limit data?

### ISSUE THREAD

**Issue by 55hyan** [zblz/naima#153]
How can we deal with the upper limit datas when we use naima for fitting? (Such as RX J1713.7-3946, there are several upper limit datas in the Fermi observation, when we do the fitting, how should we consider?).

**Comment by zblz** [comment]
naima deals with them by adding a certain value to the log-likelihood whenever the UL is violated by the model, otherwise they have no effect on the likelihood. This value depends on the confidence level of the UL. 

I'm not sure what you question is. Do you mean whether you should include them in the spectrum used for the fitting? See the [data format](https://naima.readthedocs.io/en/latest/dataformat.html) docs page for more info on how to do that.

**Comment by 55hyan** [comment]
Yes, I don't know how to include the upper limits in the data format, but I have got it now. Thanks.

**Comment by 55hyan** [comment]
I am also interested in the secondary electron spectrum from proton-proton interaction, did you have any update for this part?

**Comment by zblz** [comment]
Secondary spectrum is not yet computed by naima, there is an issue to track progress on that: #70. 

I'll close this issue as the UL issue has been resolved.
