### ISSUE TITLE
error with matplotlib

### ISSUE THREAD

**Issue by astrolog1986** [zblz/naima#159]
Dear all,

I installed naima by creating an environment with anaconda. Then when I try to use it, the following error appears
"WARNING: Interactive fitting is not available because matplotlib is
not installed: /usr/lib64/libxcb-xlib.so.0: undefined symbol:
_xcb_lock_io [naima.core]"

but I have matplotlib installed. The fit continues without opening the window for interactive fitting.
Can you please help me to solve this issue?

Thank you in advance

**Comment by zblz** [comment]
The error message could be improved. Even with matplotlib installed, some backends might not be properly installed so that when importing some matplotlib modules an exception is thrown. Searching for the error you posted brings me [to this anaconda issue](https://github.com/ContinuumIO/anaconda-issues/issues/1068) which might be related. 

Have you tried setting a different matplotlib backend? Try setting
```python
import matplotlib
matplotlib.use('TkAgg')
```
before all other imports.
