### ISSUE TITLE
Make h5py an optional dependency again?

### ISSUE THREAD

**Issue by cdeil** [zblz/naima#88]
The Gammapy docs build on readthedocs is currently broken,
because we try to `pip install naima`, which tries to `pip install `h5py` which fails:
https://readthedocs.org/projects/gammapy/builds/3287163/

I see you've make `h5py` a required dependency of naima in https://github.com/zblz/naima/commit/056f1f70e9eab040eb23c548029cdad4d56d1e02 .

Would it make sense to make `h5py` an optional dependency?
Alternatively - any advice how to get the RTD Sphinx build working again?

**Comment by zblz** [comment]
Ouch, sorry about that! I'd rather keep it as an install-time dependency, because I think `save_run`/`read_run` functions will be quite useful now that they actually save most relevant stuff.

For the naima docs I used a trick described in the readthedocs docs that allows to trick the setup into thinking a package is already installed. See the changes to `docs/conf.py` in 535c00af1f2ef37. If you think it's OK I can do a PR in gammapy adding that.

**Comment by cdeil** [comment]
Feel free to close this issue, unless you want to change something in naima.

We can keep https://github.com/gammapy/gammapy/pull/343 open as a reminder that we have to find a solution in Gammapy if we want to use naima on readthedocs in the future.
